### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by gr2m** [octokit/rest-action#1]
My current idea is that we would have a single repository which will include actions for every relevant REST API endpoint. 

```yml
  runs: actions/rest/issues/create@v1
  with:
    title: 'This is a title'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

`owner` and `repo` parameters are defaulting to the current repository and the request are authenticated using GITHUB_TOKEN.

The response body is stored in outputs, so it can be used in subsequent steps.

**Comment by gr2m** [comment]
Besides `octokit/rest-action` I am currently thinking of creating `octokit/request-action` and `octokit/graphql-action`

Creating an issue with `octokit/request-action` could look like this

```yml
runs: octokit/request-action@v1.x
  with:
    route: 'POST /repos/:owner/:repo/issues'
    title: 'This is a title'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Creating an issue with `octokit/graphql-action` could look like this

```yml
runs: octokit/graphql-action@v1.x
  with:
    query: |
      mutation($repositoryId:ID!, $title:String!) {
        createIssue(input:{repositoryId: $repositoryId, title: $title}) {
          issue {
            number
          }
        }
      }
    title: 'This is a title'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
